### ISSUE TITLE
居中问题

### ISSUE THREAD

**Issue by canhuah** [simplezhli/RecyclerViewExtensionsDemo#1]
有办法让初始化的时候就居中吗  不主动去滑动

**Comment by simplezhli** [comment]
@canhuah 你说的居中是指第一个Item还是什么。不过这类需求可以自定义`SnapHelper`实现。

**Comment by canhuah** [comment]
想要默认第二个item居中展示呢？因为默认都是第一个在左边

**Comment by simplezhli** [comment]
@canhuah 试试`mRecyclerView.smoothScrollToPosition(1);`
